config/routes.rb
Rails.application.routes.draw do

  get 'users/:id/edit' => "public/users#edit", as: "user_edit"
  get 'users/update'
  get 'homes/top'
  get 'homes/about'
# 顧客用 
  devise_for :users, skip: [:passwords],controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

# 管理者用
 devise_for :admin,skip: [:registrations, :passwords] , controllers: {
     sessions: "admin/sessions"
   }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  scope module: :public do
    root to: "homes#top" 
  
    get "/about" =>"homes#about",as: 'about'
    get "/users/mypage" =>"users#mypage",as: 'mypage'
    get "/users/information/edit" =>"users#edit",as: 'edit'
    patch "/users/information" =>"users#update",as: 'update'
    get "/movies/search" =>"movies#search",as: 'search'
    get "users/unsubscribe" => "users#unsubscribe",as: 'unsubscribe'
    patch "users/withdrawal" => "users#withdrawal",as: 'withdrawal'
    resources :movies
    resources :reviews
    resources :comments
  
  end
  
   get '/admin' => "admin/homes#top"
  namespace :admin do
 
    delete 'reviews/:id' => 'reviews#destroy'
    resources :movies
    resources :users
    resources :homes
    resources :genres
    resources :reviews
    resources :comments
    
  end
 
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :user
    belongs_to :review
    
     validates :body, presence: true
    
end

app/models/genre.rb
class Genre < ApplicationRecord
    has_many :movie_genres, dependent: :destroy
    has_many :movies, through: :movie_genres
end

app/models/movie.rb
class Movie < ApplicationRecord
    has_many :movie_genres, dependent: :destroy
    has_many :genres, through: :movie_genres
    has_many :reviews
end

app/models/movie_genre.rb
class MovieGenre < ApplicationRecord
  belongs_to :movie
  belongs_to :genre
end

app/models/public.rb
module Public
  def self.table_name_prefix
    'public_'
  end
end

app/models/review.rb
class Review < ApplicationRecord
    belongs_to :movie
    belongs_to :user
    has_many :comments
    
    validates :review_contents, presence: true
    
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :reviews
  has_many :comments
  
  validates :name, uniqueness: true, length: { in: 2..20 }
  validates :introduction, length: { maximum: 100 }
         
end

app/controllers/admin/comment_controller.rb
class Admin::CommentController < ApplicationController
  def new
  end

  def create
  end

  def index
  end

  def show
  end
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController

before_action :authenticate_admin!

 def index
    @genres = Genre.all
 end

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController

before_action :authenticate_admin!

  def top
    @reviews = Review.all
  end

    
   def destroy
      review =Review.find(params[:id])
      review.destroy
      redirect_to admin_path
   end

end

app/controllers/admin/movies_controller.rb
class Admin::MoviesController < ApplicationController
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController

before_action :authenticate_admin!

    def index
      @users = User.all
    end

    def show
      @user = User.find(params[:id])
      @reviews = @user.reviews
    end

    def edit
      @user = User.find(params[:id])
    end

    def update
      #byebug
      @user = User.find(params[:id])
      if @user.update(user_params)
        redirect_to admin_user_path(@user.id)
      else
        render :edit
      end
    end
    
  private
    def user_params
      params.require(:user).permit(:name, :email,:introduction, :is_deleted )
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    
   before_action :configure_permitted_parameters, if: :devise_controller?
 #  before_action :is_matching_login_user, only: [:edit, :update]

   def after_sign_in_path_for(resource)
    case resource
    when Admin
      admin_path
    when User
      root_path
    end
   end
   
   def after_sign_out_path_for(resource_or_scope)
    if resource_or_scope == :user
        root_path
    elsif resource_or_scope == :admin
        new_admin_session_path
    else
        root_path
    end
   end

   protected
    
    #nameも認証条件に入るようにしている
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    end


end

app/helpers/admin/comment_helper.rb
module Admin::CommentHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/movies_helper.rb
module Admin::MoviesHelper
end

app/helpers/admin/reviews_helper.rb
module Admin::ReviewsHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/genres/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h3>登録されたジャンル一覧</h3>
      <table>
          <thead>
              <tr>
                  <th></th>
              </tr>
          </thead>
        <tbody>
        <% @genres.each do |genre| %>
        <tr>
          <td>
            <%= genre.name %>
          </td>
        </tr>
        <% end %>
        </tbody>
      </table>
    </div>    
  </div>    
</div>    

app/views/admin/users/edit.html.erb
<div class="container">
<%= form_with model: @user,url: admin_user_path(@user.id),method: :patch do |f| %>
<h1><%= @user.name %>さんの会員情報編集</h1>

<table>
  <tr>
    <th>会員ID</th>
    <td><%= @user.id %></td>
  </tr>
  <tr>
    <th>名前</th>
    <td><%= f.text_field :name %>
    </td>
  </tr>
  <tr>
    <th>メールアドレス</th>
    <td><%= f.text_field :email %></td>
  </tr>
  <tr>
  <tr>
    <th>ひとこと</th>
    <td><%= f.text_field :introduction %></td>
  </tr>
  <tr>
    <th>会員ステータス</th>
    <td><%= f.radio_button :is_deleted, :false %>有効
        <%= f.radio_button :is_deleted, :true %>退会
    </td>
  </tr>
  <tr>
    <td><%= f.submit "変更を保存",class:"btn btn-sm btn-success" %></td>
  </tr>
<% end %>
</table>
</div>

app/views/admin/users/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
     <h3>会員一覧</h3>
      <table>
       <thead>
         <tr>
            <th>会員ID</th>
            <th>氏名</th>
            <th>メールアドレス</th>
            <th>ステータス</th>
         </tr>
       </thead>
  
       <tbody>  
        <% @users.each do |user| %>
        <tr>
        <td>
          <%= user.id %>
        </td>
        <td><%= link_to admin_user_path(user.id) do %>
          <%= user.name %>
          <% end %>
        </td>
        <td>
           <%= user.email %>
        </td>
        <td>
          <% if user.is_deleted == false %>
          <%= "有効" %>
          <% else %>
          <%= "退会" %>
          <% end %>
        </td>
        </tr>
        <% end %>
       </tbody>
     </table>
    </div>
  </div>
</div>

app/views/admin/users/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
   <h1><%= @user.name %>
    の会員詳細
   </h1>

    <table>
     <tr>
       <th>会員ID</th>
       <td><%= @user.id %></td>
     </tr>
     <tr>
       <th>氏名</th>
       <td><%= @user.name %>
       </td>
     </tr>
     <tr>
       <th>メールアドレス</th>
       <td><%= @user.email %></td>
     </tr>
     <tr>
       <th><label for="user_introduction">ひとこと。</label></th>
       <td><%= @user.introduction %></td>
     </tr>
     <tr>
       <th>会員ステータス</th>
       <td><% if @user.is_deleted == false %>
         <%= "有効" %>
         <% else %>
         <%= "退会" %>
         <% end %>
       </td>
     </tr>
     <tr>
       <td>
         <%= link_to "編集する",edit_admin_user_path(@user.id),class:"btn btn-sm btn-success" %>
       </td>
     </tr>
    </table>
    <table>
       <head>
         <tr>
           <th>映画タイトル</th>
           <th>レビュー内容</th>
           <th></th>
         </tr>
       </head>
       <% @reviews.each do |review| %>
       <tbody>
           <td><%= review.movie.title %></td>
           <td><%= review.review_contents %></td>
           <td><%= link_to "詳細", admin_review_path(review.id), class:"btn btn-sm btn-info" %></td>
       </tbody>
       <% end %>
    </table>
    </div>
  </div>
</div>