config/routes.rb
Rails.application.routes.draw do

  get 'users/:id/edit' => "public/users#edit", as: "user_edit"
  get 'users/update'
  get 'homes/top'
  get 'homes/about'
# 顧客用 
  devise_for :users, skip: [:passwords],controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

# 管理者用
 devise_for :admin,skip: [:registrations, :passwords] , controllers: {
     sessions: "admin/sessions"
   }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  scope module: :public do
    root to: "homes#top" 
  
    get "/about" =>"homes#about",as: 'about'
    get "/users/mypage" =>"users#mypage",as: 'mypage'
    get "/users/information/edit" =>"users#edit",as: 'edit'
    patch "/users/information" =>"users#update",as: 'update'
    get "/movies/search" =>"movies#search",as: 'search'
    get "users/unsubscribe" => "users#unsubscribe",as: 'unsubscribe'
    patch "users/withdrawal" => "users#withdrawal",as: 'withdrawal'
    resources :movies
    resources :reviews
    resources :comments
  
  end
  
   get '/admin' => "admin/homes#top"
  namespace :admin do
 
    delete 'reviews/:id' => 'reviews#destroy'
    resources :movies
    resources :users
    resources :homes
    resources :genres
    resources :reviews
    resources :comments
    
  end
 
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :user
    belongs_to :review
    
     validates :body, presence: true
    
end

app/models/genre.rb
class Genre < ApplicationRecord
    has_many :movie_genres, dependent: :destroy
    has_many :movies, through: :movie_genres
end

app/models/movie.rb
class Movie < ApplicationRecord
    has_many :movie_genres, dependent: :destroy
    has_many :genres, through: :movie_genres
    has_many :reviews
end

app/models/movie_genre.rb
class MovieGenre < ApplicationRecord
  belongs_to :movie
  belongs_to :genre
end

app/models/public.rb
module Public
  def self.table_name_prefix
    'public_'
  end
end

app/models/review.rb
class Review < ApplicationRecord
    belongs_to :movie
    belongs_to :user
    has_many :comments
    
    validates :review_contents, presence: true
    
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :reviews
  has_many :comments
  
  validates :name, uniqueness: true, length: { in: 2..20 }
  validates :introduction, length: { maximum: 100 }
         
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController

before_action :authenticate_admin!

  def top
    @reviews = Review.all
  end

    
   def destroy
      review =Review.find(params[:id])
      review.destroy
      redirect_to admin_path
   end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    
   before_action :configure_permitted_parameters, if: :devise_controller?
 #  before_action :is_matching_login_user, only: [:edit, :update]

   def after_sign_in_path_for(resource)
    case resource
    when Admin
      admin_path
    when User
      root_path
    end
   end
   
   def after_sign_out_path_for(resource_or_scope)
    if resource_or_scope == :user
        root_path
    elsif resource_or_scope == :admin
        new_admin_session_path
    else
        root_path
    end
   end

   protected
    
    #nameも認証条件に入るようにしている
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    end


end

app/helpers/admin/comment_helper.rb
module Admin::CommentHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/movies_helper.rb
module Admin::MoviesHelper
end

app/helpers/admin/reviews_helper.rb
module Admin::ReviewsHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Movies</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
   <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
       <div class="container">
         <a class="navbar-band" href="/">
           <span>あなたの観たい映画は？</span>
         </a>
         <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                        aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
           <span class="navbar-toggler-icon"></span>
         </button>
         <div class="collapse navbar-collapse" id="navbarNavDropdown">
           <ul class="navbar-nav ml-auto">
            <% if user_signed_in? %>
             <li>
              <%= link_to root_path,method: :get, class:'nav-link text-light' do %>
                <i class="fas fa-home"></i> Home
              <% end %>
             </li>
             <li>
              <%= link_to search_path,method: :get,class:'nav-link text-light' do %>
               <i class="fas fa-search"></i></i>Movies Search
              <% end %>
             </li>
             <li>
              <%= link_to reviews_path,method: :get,class:'nav-link text-light' do %>
              <i class="fal fa-comment-edit"></i>Reviews
              <% end %>
             </li>
             <li>
              <%= link_to mypage_path,method: :get, class:'nav-link text-light' do %>
                <i class="fas fa-users"></i> Mypage
              <% end %>
             </li>
             <li>
              <%= link_to destroy_user_session_path, method: :delete, class:'nav-link text-light' do %>
                <i class="fas fa-sign-out-alt"></i></i> Log out
              <% end %>
             </li>
            <% elsif admin_signed_in? %>
             <li>
              <%= link_to admin_path,method: :get,class:'nav-link text-light' do %>
              <i class="fas fa-film"></i>Reviews
              <% end %>
             </li>
             <li>
              <%= link_to  admin_users_path,method: :get,class:'nav-link text-light' do %>
               <i class="fas fa-users"></i>Users
              <% end %>
             </li>
             <li>
              <%= link_to  admin_comments_path,method: :get,class:'nav-link text-light' do %>
               <i class="far fa-comments"></i>Comment
              <% end %>
             </li>
             <li>
              <%= link_to admin_genres_path,method: :get,class:'nav-link text-light' do %>
                <i class="fas fa-film"></i>Genres
              <% end %>
             </li>
             <!--<li>-->
             <!-- <%#= link_to admin_reviews_path,method: :get,class:'nav-link text-light' do %>-->
             <!-- <i class="fas fa-film"></i>Reviews-->
             <!-- <%# end %>-->
             <!--</li>-->
             <li>
              <%= link_to destroy_admin_session_path,method: :delete,class:'nav-link text-light' do %>
               <i class="fas fa-sign-out-alt"></i></i> Log out
              <% end %>
             </li>
            <% else %>
              <li>
              <%= link_to root_path,method: :get, class:'nav-link text-light' do %>
                <i class="fas fa-home"></i> Home
              <% end %>
             </li>
             <li>
               <%= link_to about_path, method: :get, class:'nav-link text-light' do %>
                 <i class="fas fa-link"></i> About
               <% end %>
             </li>
             <li>
              <%= link_to search_path,method: :get,class:'nav-link text-light' do %>
               <i class="fas fa-search"></i>Movies Search
              <% end %>
             </li>
             <li>
              <li>
              <%= link_to reviews_path,method: :get,class:'nav-link text-light' do %>
              <i class="fas fa-comment-edit"></i>Reviews
              <% end %>
             </li>
             <li>
               <%= link_to new_user_registration_path, class:'nav-link text-light' do %>
                 <i class="fas fa-user-plus"></i> Sign up
               <% end %>
             </li>
             <li>
               <%= link_to new_user_session_path, class:'nav-link text-light' do %>
                 <i class="fas fa-sign-in-alt"></i> Log in
               <% end %>
             </li>
            
             <% end %>
           </ul>
        </div>
      </div>
   </nav>     
   </header>
   <%= yield %>
  </body>
</html>